Lef dev/2504 clean react config oul
lefevbre-organization/eShopOnContainers pull request #134
Opened 2021-07-22 11:52 UTC by jlopezdetrinidad

2021-07-23 10:14 UTC, freyes-lef approved these changes
para que sirve window.RELEASE? deberia estar en el fichero de inyeccion para desplegar?
WEBSPELLCHECKER me genera la misma duda

2021-07-23 10:17 UTC, freyes-lef commented on deploy/k8s-lef/helm/react_dev.yaml
> +  window.BASE_DEV='https://lexbox-pre'
no se porque lo cambias, deberia ser base_PRE

2021-07-23 10:19 UTC, freyes-lef commented on src/Web/WebGoogleClient/Client/public/config.js
> +window.URL_LEXON = "http://localhost:8080"
entiendo que este valor tiene que estar compuesto por base + cm_lex como los demás, no?

2021-07-23 10:22 UTC, freyes-lef commented on src/Web/WebGoogleClient/Client/public/config.js
> +window.URL_LEXON = "http://localhost:8080"
No se porque no se usa un compuesto de base y cn_lexon

2021-07-23 10:31 UTC, freyes-lef commented on src/Web/WebLexonClient/Client/src/constants/index.js
> +export const COMPANIES = "lex/Lexon/companies"
Creo que podria hacerse de varias maneras mas simplificado:
Opcion 1:
 PATH_LEXON = "lex/Lexon"
PATH_CLASSIFICATION = "/classifications"
PATH_ENTITIES = "/entities"
....
Opción 2: (creo que la más adecuada para no ser muy exagerados en la composición
PATH_CLASSIFICATION = "lex/Lexon/classifications"
PATH_ENTITIES = "lex/Lexon/entities"
....

Pero no puede haber de ninguna CLASSIFICATIONS_ADD y RESULTS .... eso seria poner el ultimo path en la lllamda diretamente

2021-07-23 10:32 UTC, freyes-lef commented on src/Web/WebOffice365Client/Client/public/config.js
> +window.BASE_DEV='https://lexbox-test'
No entiendo porque quedan dos BASE_DEV

2021-07-23 10:34 UTC, freyes-lef requested changes
verifica los comentarios que te he puesto ...el más importante es lode BASE_DEV por BASE_PRE

2021-07-23 13:29 UTC, jlopezdetrinidad commented on src/Web/WebGoogleClient/Client/public/config.js
> +window.URL_LEXON = "http://localhost:8080"
window.URL_LEXON es para la connexion entre lexon y el iframe del calendario

2021-07-26 06:48 UTC, freyes-lef commented on src/Web/WebLexonClient/Client/src/constants/index.js
> +export const PATH_CLASSIFICATIONS_ADD = "/classifications/add"
Ahora queda mucho mejor, aunque para las próximas intenta mantener el pattern [DRY ](https://es.wikipedia.org/wiki/No_te_repitas)
* ${window.BASE}-${window.GW_LEX}/${window.API_V1}/${PATH_LEXON}${PATH_CLASSIFICATIONS}/add
* ${window.BASE}-${window.GW_LEX}/${window.API_V1}/${PATH_LEXON}${PATH_CLASSIFICATIONS}/remove

2021-07-26 06:51 UTC, freyes-lef approved these changes
Revisa el comentario que te he puesto, pero por mi podemos darlo por aprobado

2021-07-26 13:00 UTC, merged